# Generated by Django 5.1.5 on 2025-05-19 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Ad_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Username', models.CharField(max_length=255, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Contact_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('Doc_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=225)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('Specialization', models.CharField(max_length=225)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('Contact_no', models.CharField(max_length=15)),
                ('Payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Ch_date_time', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('P_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=225)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Address', models.TextField()),
                ('Contact', models.CharField(max_length=15)),
                ('Username', models.CharField(max_length=255, unique=True)),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('St_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=225)),
                ('Role', models.CharField(max_length=225)),
                ('Contact_no', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Username', models.CharField(max_length=225, unique=True)),
                ('Password', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('Test_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=225)),
                ('Precausions', models.JSONField(default=dict)),
                ('Requirements', models.JSONField(default=dict)),
                ('Time_for_one_person', models.IntegerField(help_text='Time in minutes.')),
                ('Payment', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DocAppointment',
            fields=[
                ('App_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('reminder_state', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appointments.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appointments.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doc_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doc_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('App_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Appointments.docappointment')),
                ('St_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appointments.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Annoucement',
            fields=[
                ('A_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Content', models.TextField()),
                ('St_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appointments.staff')),
            ],
        ),
        migrations.CreateModel(
            name='TestAppointment',
            fields=[
                ('App_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('time', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('reminder_state', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appointments.patient')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appointments.test')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Test_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('St_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appointments.staff')),
                ('App_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Appointments.testappointment')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Result_file', models.FileField(upload_to='results/')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('St_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appointments.staff')),
                ('App_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Appointments.testappointment')),
            ],
        ),
    ]
