# Generated by Django 5.1.5 on 2025-05-27 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='username',
            new_name='Username',
        ),
    ]
