# Generated by Django 5.1.5 on 2025-07-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0002_rename_username_doctor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testappointment',
            name='time',
            field=models.TimeField(max_length=20),
        ),
    ]
