# Generated by Django 5.1.5 on 2025-07-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0003_alter_testappointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docappointment',
            name='App_ID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testappointment',
            name='App_ID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
